version: '3.3'

services:
    backend:
        build:
            context: AirQuality
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart: on-failure
    
    client:
        build:
            context: web
            dockerfile: Dockerfile
        ports:
            - "8000:8081"
        volumes:
            - ./src:/etc/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on: 
            - backend